@startuml
class event.faith.Holywarrior {
+ void effect()
+ String getResult()
+ String toString()
+ String getUrl()
}
abstract class logic.building.base.School {
+ {static} int genMul
+ {static} int maintainCost
}
class logic.building.misc.Tile {
- Building building
- boolean ownByPlayer
- boolean clearingArea
+ <<Create>> Tile()
+ <<Create>> Tile(boolean)
+ <<Create>> Tile(boolean,Building)
+ boolean isOccupied()
+ void setBuilding(Building)
+ void removeBuilding()
+ Building getBuilding()
+ boolean isOwnByPlayer()
+ void setOwnByPlayer(boolean)
+ void setClearingArea(boolean)
+ boolean isClearingArea()
}
class logic.building.TownHall {
- int level
+ String url1
+ String url2
+ String url3
- boolean upgrading
+ <<Create>> TownHall()
+ void upgradeLevel()
+ String buyUpgrade()
+ boolean isUpgrading()
+ int getLevel()
+ String getUrl()
+ String toString()
}
class event.main.Earthquake {
+ void effect()
+ String getResult()
+ String toString()
+ String getUrl()
}
interface logic.building.base.Activatable {
+ boolean isActive()
+ void setActive(boolean)
+ void turnOn(boolean)
}
class logic.building.Temple {
- boolean active
+ {static} int faithGen
+ {static} int maintainCost
+ String url1
+ <<Create>> Temple()
+ void turnOn(boolean)
+ void setActive(boolean)
+ boolean isActive()
+ String getUrl()
+ String toString()
}
class event.main.Plague {
- int n
+ void effect()
+ String getResult()
+ String toString()
+ String getUrl()
}
class event.main.Drought {
- int n
+ void effect()
+ String getResult()
+ String toString()
+ String getUrl()
}
class UI.alert.EventAlertBox {
+ {static} void display(String,String,String)
}
class UI.alert.InsufficientAlert {
+ {static} void display(int)
}
class event.Raid {
- int raidPower
- boolean result
+ <<Create>> Raid(int)
+ void effect()
+ String getUrl()
+ String toString()
+ String getResult()
}
class event.main.Rebellion {
+ void effect()
+ String getResult()
+ String toString()
+ String getUrl()
}
class logic.utils.Battle {
- GameLogic gameInstance
- int raidPower
- boolean win
- Random random
- int playerPower
+ <<Create>> Battle(int)
+ void punish()
+ boolean isWinning()
+ void setRaidPower(int)
+ int getRaidPower()
}
class logic.building.Farm {
+ {static} int moneyGen
+ String url1
+ <<Create>> Farm()
+ String getUrl()
+ String toString()
}
class UI.alert.BuildingInteraction {
+ {static} void display(Tile,int,int)
}
abstract class event.base.Event {
# GameLogic gameInstance
# Random random
+ <<Create>> Event()
+ {abstract}void effect()
+ {abstract}String getResult()
+ {abstract}String toString()
+ {abstract}String getUrl()
}
class UI.alert.TownHallUpgrade {
+ {static} void display()
}
class logic.building.misc.ConstructionSite {
- int targetBuildingCode
+ String url1
+ <<Create>> ConstructionSite(int)
+ Building Construct()
+ String toString()
+ String getUrl()
}
interface logic.building.base.Damagable {
}
class logic.building.ArmySchool {
- boolean active
+ String url1
+ <<Create>> ArmySchool()
+ void turnOn(boolean)
+ void setActive(boolean)
+ boolean isActive()
+ String toString()
+ String getUrl()
}
interface logic.building.base.Demolishable {
}
class UI.alert.MercenaryAlert {
+ {static} void display(int,int)
}
class UI.alert.BuyTile {
+ {static} void display(Tile,int,int)
}
class logic.building.CampingSite {
+ String url1
- int countDay
- boolean active
- boolean success
- int successRate
+ {static} int maintainCost
- Random random
+ <<Create>> CampingSite()
+ void turnOn(boolean)
+ void setActive(boolean)
+ void accumulate()
+ void reset()
+ void explore()
+ int getSuccesRate()
+ void setSuccessRate(int)
+ boolean isActive()
+ int getCountDay()
+ boolean countDown()
+ boolean isExploring()
+ String toString()
+ String getUrl()
}
class logic.building.FarmSchool {
- boolean active
+ String url1
+ <<Create>> FarmSchool()
+ void turnOn(boolean)
+ void setActive(boolean)
+ boolean isActive()
+ String getUrl()
+ String toString()
}
class application.Main {
+ {static} Scene startScene
+ void start(Stage)
}
class UI.pane.GameLoop {
- {static} int day
- {static} GameLogic gameInstance
- {static} EventMaker eventM
+ {static} Stage st
+ {static} void startGame(Stage)
+ {static} void gameStart()
+ {static} void nextDay()
+ {static} void event()
+ {static} void raidEvent()
+ {static} void faithEvent()
+ {static} void mainEvent()
+ {static} int getDay()
}
class event.faith.Philanthropy {
+ void effect()
+ String getResult()
+ String toString()
+ String getUrl()
}
class UI.alert.YesNoScreen {
+ {static} boolean display()
}
class UI.alert.InPlague {
+ {static} void display()
}
class logic.building.misc.BuildingRuin {
+ String url1
- int buildingId
+ <<Create>> BuildingRuin(int)
+ int getBuildingId()
+ String toString()
+ String getUrl()
}
class UI.component.TileButton {
- int row
- int col
- ImageView building
+ <<Create>> TileButton(int,int)
+ void updateImage(String)
+ StackPane tileImage()
+ void setRow(int)
+ void setCol(int)
+ int getRow()
+ int getCol()
}
class event.main.Mercenary {
+ void effect()
+ String getResult()
+ String toString()
+ String getUrl()
}
class logic.utils.Player {
- int money
- int power
- int faithPercentage
- int maxBuilder
- int availableBuilder
+ <<Create>> Player()
+ int getMoney()
+ void setMoney(int)
+ void addMoney(int)
+ void subMoney(int)
+ int getPower()
+ void setPower(int)
+ void addPower(int)
+ int getFaithPercentage()
+ void setFaithPercentage(int)
+ void gainFaith(int)
+ void faithPercentageDecay()
+ int getAvailableBuilder()
+ void setAvailableBuilder(int)
+ int getMaxBuilder()
+ void setMaxBuilder(int)
+ void upgradeTownHall()
+ void useBuilder()
}
class logic.utils.GameLogic {
- int plagueCount
- int droughtCount
- boolean gameOver
- String gameEnding
- boolean win
- TownHall townHall
- int income
- int powerGrowth
- int incomeMultiplier
- int powerMultiplier
- int expense
- int faithGrowth
- Player player
- ArrayList<ArrayList<Tile>> map
- Map<Integer,Integer> buildingCost
- {static} GameLogic instance
- <<Create>> GameLogic()
+ {static} GameLogic getInstance()
+ {static} void newInstance()
+ {static} void killInstance()
- void setMap()
+ void dailyUpdate()
+ {static} void selectTile(int,int)
+ void activateBuilding(Tile)
+ void onCampingSite()
+ void offCampingSite()
+ void onArmyCamp()
+ void offArmyCamp()
+ void onArmySchool()
+ void offArmySchool()
+ void onFarm()
+ void offFarm()
+ void onFarmSchool()
+ void offFarmSchool()
+ void onTemple()
+ void offTemple()
- void clearValue()
- void initBuildingCost()
+ {static} boolean haveEnoughMoney(int)
+ {static} boolean haveEnoughBuilder()
+ void destroyBuilding(int)
+ Player getPlayer()
+ int getIncome()
+ void setIncome(int)
+ int getPowerGrowth()
+ void setPowerGrowth(int)
+ int getIncomeMultiplier()
+ void setIncomeMultiplier(int)
+ int getPowerMultiplier()
+ void setPowerMultiplier(int)
+ int getExpense()
+ void setExpense(int)
+ int getFaithGrowth()
+ void setFaithGrowth(int)
+ ArrayList<ArrayList<Tile>> getMap()
+ TownHall getTownHall()
+ Map<Integer,Integer> getBuildingCost()
+ boolean isGameOver()
+ void gameEnd()
+ boolean isWin()
+ void won()
+ String getGameEnding()
+ void setGameEnding(String)
+ void effectDrought(int)
+ void effectPlague(int)
+ boolean inPlague()
+ boolean inDrought()
}
class logic.building.ArmyCamp {
- boolean active
+ {static} int powerGen
+ {static} int maintainCost
+ String url1
+ <<Create>> ArmyCamp()
+ void turnOn(boolean)
+ void setActive(boolean)
+ String toString()
+ boolean isActive()
+ String getUrl()
}
class UI.BackgroundMusic {
- {static} MediaPlayer mediaPlayer
+ void play()
}
class UI.alert.BuyMenu {
+ {static} Stage stage
+ {static} int curRow
+ {static} int curCol
+ {static} void display(int,int)
+ {static} void stageClose()
}
abstract class logic.building.base.Building {
+ String url1
+ {abstract}String getUrl()
+ {abstract}String toString()
}
class UI.component.BuildingChoiceBox {
+ <<Create>> BuildingChoiceBox(int,String,String,int)
}
class event.main.Burglar {
- int stolenMoney
+ <<Create>> Burglar()
+ void effect()
+ String getResult()
+ String toString()
+ String getUrl()
}
class logic.building.misc.Demolishing {
+ String url1
+ String toString()
+ String getUrl()
}
class UI.alert.GameEndAlert {
+ {static} void display(String,String)
}
class logic.utils.EventMaker {
- ArrayList<Event> mainEvents
- ArrayList<Event> faithEvents
- ArrayList<Event> raidEvents
- int seqCounter
- int raidCounter
- int faithCounter
- Random random
+ <<Create>> EventMaker()
+ Event getMainEvent(int)
+ Event getFaithEvent()
+ Event getRaidEvent()
- void initiateMainEvents()
- void initiateRaidEvents()
- void initiateFaithEvents()
}
class UI.pane.IngameStage {
- GridPane playArea
+ {static} ArrayList<TileButton> map
- VBox displayArea
+ {static} Text day
+ {static} Text money
+ {static} Text power
+ {static} Text income
+ {static} Text expense
+ {static} Text faith
+ {static} Text builder
- {static} ImageView plagueStatus
- {static} ImageView droughtStatus
+ <<Create>> IngameStage()
+ {static} void update(int,int,String)
- GridPane createPlayArea()
- VBox createDisplayArea()
+ {static} void updateInfo()
+ {static} void setDroughtStatus(boolean)
+ {static} void setPlagueStatus(boolean)
}
class UI.pane.StartGame {
- Stage stage
+ <<Create>> StartGame(Stage)
}


event.base.Event <|-- event.faith.Holywarrior
logic.building.base.Building <|-- logic.building.base.School
logic.building.base.Building <|-- logic.building.TownHall
event.base.Event <|-- event.main.Earthquake
logic.building.base.Activatable <|.. logic.building.Temple
logic.building.base.Demolishable <|.. logic.building.Temple
logic.building.base.Building <|-- logic.building.Temple
event.base.Event <|-- event.main.Plague
event.base.Event <|-- event.main.Drought
event.base.Event <|-- event.Raid
event.base.Event <|-- event.main.Rebellion
logic.building.base.Demolishable <|.. logic.building.Farm
logic.building.base.Damagable <|.. logic.building.Farm
logic.building.base.Building <|-- logic.building.Farm
javafx.scene.layout.VBox <|-- UI.alert.BuildingInteraction
logic.building.base.Building <|-- logic.building.misc.ConstructionSite
logic.building.base.Activatable <|.. logic.building.ArmySchool
logic.building.base.Demolishable <|.. logic.building.ArmySchool
logic.building.base.School <|-- logic.building.ArmySchool
logic.building.base.Activatable <|.. logic.building.CampingSite
logic.building.base.Demolishable <|.. logic.building.CampingSite
logic.building.base.Building <|-- logic.building.CampingSite
logic.building.base.Activatable <|.. logic.building.FarmSchool
logic.building.base.Demolishable <|.. logic.building.FarmSchool
logic.building.base.School <|-- logic.building.FarmSchool
javafx.application.Application <|-- application.Main
event.base.Event <|-- event.faith.Philanthropy
logic.building.base.Building <|-- logic.building.misc.BuildingRuin
javafx.scene.layout.StackPane <|-- UI.component.TileButton
event.base.Event <|-- event.main.Mercenary
logic.building.base.Activatable <|.. logic.building.ArmyCamp
logic.building.Demolishable <|.. logic.building.ArmyCamp
logic.building.Damagable <|.. logic.building.ArmyCamp
logic.building.Building <|-- logic.building.ArmyCamp
javafx.scene.layout.VBox <|-- UI.component.BuildingChoiceBox
event.base.Event <|-- event.main.Burglar
logic.building.base.Building <|-- logic.building.misc.Demolishing
UI.pane.BorderPane <|-- UI.pane.IngameStage
javafx.scene.layout.VBox <|-- UI.pane.StartGame
@enduml